import Footer from "../../components/footer/Footer";
import { Header } from "../../components/header/Header";
import "./globals.css";
import { Manrope, Poiret_One } from "next/font/google";
import { Providers } from "../store/provider";
import clsx from "clsx";

const manrope = Manrope({
  weight: "400",
  subsets: ["cyrillic"],
});

const poiret = Poiret_One({
  weight: "400",
  subsets: ["cyrillic"],
});

export const metadata = {
  title: "Rates",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={clsx(manrope.className)}>
        <header className="header">
          <Header />
        </header>
        <main>
          <Providers> {children}</Providers>
        </main>
        <footer className={clsx(poiret.className)}>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
